kill-lcoins: 5
tag-duration: 10 # in seconds. Support decimal

levelup-need-kills: 5
instant-respawn: true

combat-block-commands:
  - "spawn"

# In ticks. 20 ticks = 1 second
title-fadeIn: 20
title-stay: 80
title-fadeOut: 20

death-titles:
  chiteros:
    title: "&c&lMucho chitero"
    subtitle: "&7Que malos son >:("
  pedro:
    title: "&b&lPedro &a✔"
    subtitle: "&7Pedro &a✔"
  gg:
    title: "&b&lGG"
    subtitle: "&7Moriste con honores"
  maracaqlia:
    title: "&d&lMaraca qlia"
    subtitle: "&7sapo triplehijueputa"
  paja:
    title: "&a&lOH! ME VENGO"
    subtitle: "&7Faraon Love Shady - 2020"
  abuelo:
    title: "&eMi abuelo decía:"
    subtitle: "&7Esto con los milicos no pasaba"